baseURL = 'http://ChenYingShan1114.github.io/'
title = 'Ying-Shan Chen@TW ~ $'
theme = 'erblog'
pagination.pagerSize = 10
languageCode = 'en-us'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Ying-Shan Chen"
    skills_color = "cyan"
    badge = "gray"
    quote = "gray"
    # notice = "Hello, world. This is a notification."
    # notice_color = "red"
    index_posts_num = 10
    google_search = true
    math = true

    # logo = "/self/img/logo.png"
    bio = """I’m a physicist turned visual storyteller and computational wizard, crafting stunning animations and physics-based simulations. With a strong foundation in physics and years of research and industry experience, I love merging science and art to build immersive 3D worlds. Whether simulating plasma particles through code, rigging robots in Maya, or implementing physics-based animation in Omniverse, I turn complex ideas into compelling visual stories. Dive in and explore where imagination meets code and becomes reality.
    """
    description = """ 陳盈珊 """
    copyright = "Copyright © 2025 Ying-Shan (Sandy) Chen, Steve Francia and the Hugo Authors; all rights reserved."

[[menu.main]]
    url = "/about/"
    name = "~/about"
    weight = 1

[[menu.main]]
    url = "/publications/"
    name = "~/publications"
    weight = 2

[[menu.main]]
    url = "/gallery/"
    name = "~/gallery"
    weight = 6

[[menu.main]]
    url = "/projects/"
    name = "~/projects"
    weight = 7

[[menu.icon]]
    url = "mailto:cindy1999881114@gmail.com"
    name = "envelope-o"
    weight = 1


[[menu.icon]]
    url = "https://github.com/ChenYingShan1114/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/yingshan.chen.33/"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/ying-shan-chen-4a3b30245/"
    name = "linkedin"
    weight = 1
    
